### PR TITLE
Types for next

### PR DESCRIPTION
**Pull request by 0t4u**
Contribution for progression towards the version of Shoukaku

Typings will be updated as the refactor progresses

These are not tested for production use

All info are in types [README](https://github.com/0t4u/Shoukaku/blob/next/types/README.md)

P.S. Saya gimme pats

### CODE REVIEW

**Comment by Deivu** [comment]
Is this done, if so you can mark this as ready for review

**Comment by hydrox19** [comment]
Is there any way I can also contribute to this PR like I wanna add some typings?

**Comment by Deivu** [comment]
@hydrox19  I think you could PR on his fork at branch `next` then wait for @0t4u to merge it, it will reflect the changes here

**Comment by hydrox19** [comment]
> @hydrox19 I think you could PR on his fork at branch `next` then wait for @0t4u to merge it, it will reflect the changes here

Alright

**Comment by 0t4u** [comment]
Types have now been updated to reflect upstream commit E976088AB1601B083E76F02E12D232B3250F1D27

**Comment by 0t4u** [comment]
@Deivu can I just merge this...

**Pull request merged**
