### PR TITLE
Fix player not moved correctly if not playing

### PR DESCRIPTION
**Pull request by flav-code**

### CODE REVIEW

**Comment by Deivu** [comment]
Could you explain why do we need update() since resume uses playerData internally on trying to resume?

**Comment by flav-code** [comment]
well if you do this.resume() it will send the info to the node only if the player is playing so if you move an inactive player the new node won't get the info

**Comment by Deivu** [comment]
I think you can safely remove the this.track check in resume

**Comment by flav-code** [comment]
Saya can you merge it ?

**Review by Deivu — APPROVED** [review]

**Pull request merged**
