### PR TITLE
use petitio, a faster zero dependency fetching library.

### PR DESCRIPTION
**Pull request by diced**
Continuation of https://github.com/Deivu/Shoukaku/pull/37#issuecomment-818393860, and I guess fixes lavalink URL's on this branch as I created feature/petitio from master.

### CODE REVIEW

**Comment by Deivu** [comment]
On the side node, I assume this is already tested?

**Comment by takase1121** [comment]
Just a little question: does lavalink send other 2XX code? Fetch API's ok could include other 2XXs.

**Comment by diced** [comment]
> On the side node, I assume this is already tested?

I haven't been able to test it as I was pretty busy, it would be great if you could.

**Comment by diced** [comment]
> Just a little question: does lavalink send other 2XX code? Fetch API's ok could include other 2XXs.

Not sure but, that's an easy fix:
```js
res.status >= 200 && res.statusCode < 300
```
I'll make sure to commit when I've got time.

**Comment by diced** [comment]
These last 2 commits fix the statusCode and changes AbortError to HeadersTimeoutError

**Comment by diced** [comment]
Actually it could error out with BodyTimeoutError or ConnectTimeoutError or HeadersTimeoutError

**Comment by Deivu** [comment]
I don't have much time on my plate right now, if tested, you could guys let me know, so I can merge this into the next branch

**Comment by Deivu** [comment]
Merging this as I will slowly start to work on v2

**Pull request merged**
