### PR TITLE
Resumable state

### LINKED ISSUE #118: When restarting the bot and leaving Lavalink running it wont reconnect to the old player
When you try to leave Lavalink running (with a player running) and restart the bot, it won't reconnect to the player that is running rather create a new one. So the old player which is running cant be controlled anymore until it has a timeout.

Would it be possible to reconnect to the old player and control it again?

### PR DESCRIPTION
**Pull request by 0t4u**
Provides a method for dumping of internal state so that it can be recreated in a new Shoukaku instance.
This would be useful when a bot restarts for updates, as it minimises disruption for users.
This closes #118.

### CODE REVIEW

**Comment by 0t4u** [comment]
p.s. code has not been tested, further investigation is required to see if this is reliable, and see how much resources it consumes

**Comment by flav28** [comment]
> p.s. code has not been tested, further investigation is required to see if this is reliable, and see how much resources it consumes

I can test on my side and correct bugs

**Comment by JoniXTech** [comment]
but how can you avoid errors like these:

{
  code: 4006,
  reason: 'Session is no longer valid.',
  byRemote: true,
  guildId: '972875190071595058',
  op: 'event',
  type: 'WebSocketClosedEvent'
}

or is it possible to create a new session Id (discord) for the player update?

**Comment by flav28** [comment]
> but how can you avoid errors like these:
> 
> { code: 4006, reason: 'Session is no longer valid.', byRemote: true, guildId: '972875190071595058', op: 'event', type: 'WebSocketClosedEvent' }
> 
> or is it possible to create a new session Id (discord) for the player update?

idk

**Comment by 0t4u** [comment]
PR needs to be updated for #158 in the future.

**Pull request closed without merging**
