### PR TITLE
Fix(typings): nullable params

### PR DESCRIPTION
**Pull request by Orchit07**

### CODE REVIEW

**Comment by kakarot-dev** [comment]
There is a pr i made to your fork
mind checking it out?

**Comment by kakarot-dev** [comment]
@Deivu mind check if this pr’s changes are valid? https://github.com/Orchit07/Shoukaku/pull/2

@Orchit07 pls dont merge [this](https://github.com/Orchit07/Shoukaku/pull/2) until deivu says so, Thanks!

**Comment by kakarot-dev** [comment]
The reason i didnt open a Seperate pr was because this already had the changes need ( and also cuz i was lazy to write text )

**Comment by kakarot-dev** [comment]
@Orchit07 you can go ahead and merge my pr
i think it’s finished

**Comment by Orchit07** [comment]
Thanks @kakarot-dev.

**Pull request merged**
