### PR TITLE
Typings and other minor changes

### PR DESCRIPTION
**Pull request by hydrox19**
Please check it thoroughly before merging, as it contains some breaking changes

### CODE REVIEW

**Comment by Deivu** [comment]
The breaking change on the TrackList must be removed, as that would break semver, aka the old structure must remain there.
raw on Track will never be null, nor the info property for it, so the ? is not really needed there

The `TrackList` change however can be implemented in v3 but that isn't happening yet. Other than that this is fine

**Comment by hydrox19** [comment]
> The breaking change on the TrackList must be removed, as that would break semver, aka the old structure must remain there.
> raw on Track will never be null, nor the info property for it, so the ? is not really needed there
> 
> The `TrackList` change however can be implemented in v3 but that isn't happening yet. Other than that this is fine

Alright wait for few sec

**Comment by hydrox19** [comment]
Ok check it again and lemme know if there's any issue

**Comment by Deivu** [comment]
Seems ok thanks for the pr

**Pull request merged**
