### PR TITLE
Remove global volume we use the filter volume

### PR DESCRIPTION
**Pull request by flav-code**
When we move it changes the global volume while we use the volume of the filters

### CODE REVIEW

**Comment by Deivu** [comment]
Could you elaborate how it behaves?

**Comment by flav28** [comment]
> Could you elaborate how it behaves?

With your code we use the filter volume and you put for the global volume the value of the filter which is very small so the volume is very low so you must remove this line

**Comment by Deivu** [comment]
Based on discussion in Lavalink, I will put this on hold until I decide on how I would tackle this.

**Comment by Deivu** [comment]
Fixed in commits above `76dca52`

**Pull request closed without merging**
