### PR TITLE
`Added plugin support`

### PR DESCRIPTION
**Pull request by AADI0009**

### CODE REVIEW

**Comment by KagChi** [comment]
You dont stream, directly from Deezer. while you claiming it as "*A plugin to stream audio from deezer*" https://www.npmjs.com/package/stone-deezer?activeTab=explore

**Comment by AADI0009** [comment]
> You dont stream, directly from Deezer. while you claiming it as "_A plugin to stream audio from deezer_" https://www.npmjs.com/package/stone-deezer?activeTab=explore

sorry i mistyped it
it searches the query from available sources

**Comment by Deivu** [comment]
You should clarify that this needs kazagumo to work, and add kazagumo on top of your plugin

**Comment by AADI0009** [comment]
> You should clarify that this needs kazagumo to work, and add kazagumo on top of your plugin

alright actually this is my first ever npm package and pull request so i don’t actually know much about it my bad

**Review by AADI0009 — COMMENTED** [review]
Fixed

**Comment by 0t4u** [comment]
IMHO Shoukaku README shouldn't be used to promote plugins, especially a Kazagumo plugin.

**Review by Deivu — APPROVED** [review]

**Pull request merged**
