### PR TITLE
Adds support for Lavalink filters

### PR DESCRIPTION
**Pull request by Deivu**
This will add support for Lavalink Filters and also contains various quality of life changes and bug fixes

Progress:
- [x] Code
- [x] JSDoc 
- [x] Typings 
- [ ] Stability and Bug Testing

To hop in the testing train just do
```
npm install git://github.com/Deivu/Shoukaku.git#filters --save
```

For feedback and issues with it, just comment in this thread.

### CODE REVIEW

**Comment by Uthsho** [comment]
Just A Suggestion, There could be a method called setFilters
where you can simultaneously update filters to lavalink and send instead of like using setTremolo & setVibrato.
like 
`
setFilter({
tremolo: {...},
timescale: {...}
})
`

**Comment by Deivu** [comment]
> Just A Suggestion, There could be a method called setFilters
> where you can simultaneously update filters to lavalink and send instead of like using setTremolo & setVibrato.
> like
> `setFilter({ tremolo: {...}, timescale: {...} })`

@Uthsho Implemented in latest commit
image

**Comment by Milo123459** [comment]
Have we got any progress on this PR for when it'll be merged? I've heard that you need a special lavalink server for this to work, but, I don't know.

**Comment by Kyosodev** [comment]
> Have we got any progress on this PR for when it'll be merged? I've heard that you need a special lavalink server for this to work, but, I don't know.

You need one of the dev builds, the latest view have it. The PR works fine on 132k+ guilds as I've been using it for the last few weeks now, I suppose Saya could merge it soon

**Comment by Deivu** [comment]
> Have we got any progress on this PR for when it'll be merged? I've heard that you need a special lavalink server for this to work, but, I don't know.

I'm working on a revamp on my bot right now, and there is also some "minor issues" with this PR that I need to fix after I finish the revamp on the bot, so I can test both things at the same time. I'm not sure how major this issue is, but seeing how other users seems to not have it, it could be a really minor one

**Comment by Milo123459** [comment]
Thanks for some insight.

**Comment by Milo123459** [comment]
Still confused, would this require a custom Lavalink server?

**Comment by Deivu** [comment]
Not custom, but the one compiled from dev branch

**Comment by Milo123459** [comment]
Thanks

**Comment by cxllm** [comment]
Any plans for the new rotation and distortion filters yet?

**Comment by Uthsho** [comment]
You can use my fork. It has the new filters.

**Comment by Deivu** [comment]
> Any plans for the new rotation and distortion filters yet?

I usually add the new filters after the PRs have been merged, seeing it's merged, it would be sooner or later

**Comment by Deivu** [comment]
New filter effects have been added, though I haven't tested it yet

**Comment by Uthsho** [comment]
I'll test them out when I can

**Comment by Uthsho** [comment]
Seems like ShoukakuGroupFiltersOptions doesn't have rotation, distortion in the typings

**Pull request merged**
