### PR TITLE
add more sources in Lavalink sources

### PR DESCRIPTION
**Pull request by kakarot-dev**
Added some more sources inside the type "LavalinkSources"

Also do i need to update the enum "searchtypes" too?

### CODE REVIEW

**Comment by KagChi** [comment]
isnt you only can search in ytm, yt, sc? i think this is useless

**Comment by kakarot-dev** [comment]
Are u referring to the entire pr or just my comment on updating the “search types”

**Comment by thrace19** [comment]
This PR seems useless https://github.com/Deivu/Shoukaku/blob/master/types/index.d.ts#L92

**Comment by hydrox19** [comment]
This PR seems useless https://github.com/Deivu/Shoukaku/blob/master/types/index.d.ts#L92

**Comment by KagChi** [comment]
> Are u referring to the entire pr or just my comment on updating the “search types”

entire

**Comment by kakarot-dev** [comment]
Oh kk, I’ll close it then

**Pull request closed without merging**
