### PR TITLE
Small fix in library readme

### PR DESCRIPTION
**Pull request by kakarot-dev**

### CODE REVIEW

**Comment by kakarot-dev** [comment]
I'll add some more steps on how to implement a different lib too instead of referring to the Discordjs file

**Comment by Deivu** [comment]
You could instead make it `13.x.x` indicating it will be compatible for any Discord.JS v13 patch and minor semvers

**Comment by kakarot-dev** [comment]
> You could instead make it `13.x.x` indicating it will be compatible for any Discord.JS v13 patch and minor semvers
No cuz the node version 16.6.0 blocks them from doing so

**Comment by kakarot-dev** [comment]
Discordjs version 13.0.0 was supported by node 16.x 
But shoukaku specifically supports 16.6

**Comment by kakarot-dev** [comment]
https://github.com/kakarot-dev/Shoukaku/blob/df2b7dd16e6f065c6a99c931ff960e32ea386274/package.json#L23

**Comment by Deivu** [comment]
13.1.0 should be supported as well so, we can probably just say 13.0.1 or newer

**Comment by hydrox19** [comment]
According to my view `13.x.x` gives a clear idea that it will support all patches and minor semver

**Comment by kakarot-dev** [comment]
> 13.1.0 should be supported as well so, we can probably just say 13.0.1 or newer

Ok I'll update to that

**Comment by kakarot-dev** [comment]
Done

**Comment by Deivu** [comment]
Ok looking on this, we could downgrade the minimum supported node to 16.0.0 or newer, then change the supported to `13.x.x`

**Comment by kakarot-dev** [comment]
Oki, I'll do it

**Comment by kakarot-dev** [comment]
Btw, while merging this, pls use the squash and merge option if possible

**Comment by Deivu** [comment]
Make the version `13.x.x`

**Comment by Deivu** [comment]
Seems ok thanks for the pr

**Pull request merged**
