### PR TITLE
chore: some stuff

### PR DESCRIPTION
**Pull request by kakarot-dev**
I fixed all the “guidlId” and “channelId” and also “shardId”

idk what more are left, so, yea ……

feeel to turn down this pr

### CODE REVIEW

**Comment by Deivu** [comment]
Did you update the docs and typings?

**Comment by kakarot-dev** [comment]
> Did you update the docs and typings?

if you mean the /docs direactory, no
but the typings is updated

**Comment by kakarot-dev** [comment]
how to update the docs dir?
it seems too complex xd

**Comment by Deivu** [comment]
Nah just the typings and docs on files, /docs are auto generated and is not included, also did you test it on a test bot before hand

**Comment by kakarot-dev** [comment]
nope, im planning to test it tommorow as it is almost night here

also for the docs, do i need to do `npm run docs:build` ??

**Comment by Orchit07** [comment]
> Nah just the typings and docs on files, /docs are auto generated and is not included, also did you test it on a test bot before hand
I'll test it

**Comment by Orchit07** [comment]
image
hmmm, i think it's not come from my lavalink or my code. Bot can't to play the track and track position always 0

**Comment by Deivu** [comment]
check lavalink logs

**Comment by Orchit07** [comment]
> check lavalink logs

image

**Comment by Orchit07** [comment]
image
👀

**Comment by Orchit07** [comment]
Fixed on [this](https://github.com/kakarot-dev/Shoukaku/pull/2) PR

**Comment by kakarot-dev** [comment]
Ty, missed that

**Comment by kakarot-dev** [comment]
I fixed it up
to test this pr do: `npm install kakarot-dev/Shoukaku#next`

**Comment by Orchit07** [comment]
> @Deivu for the docs, do i need to do `npm run docs:build` ??
> 
> And @Orchit07 ty so much for testing this for me!

Add github action for auto build docs on [this](https://github.com/kakarot-dev/Shoukaku/pull/3) PR

**Comment by kakarot-dev** [comment]
> > @Deivu for the docs, do i need to do `npm run docs:build` ??
> > And @Orchit07 ty so much for testing this for me!
> 
> Add github action for auto build docs on [this](https://github.com/kakarot-dev/Shoukaku/pull/3) PR

problem is the actions are run on stateless containers, those wont be permanent

**Comment by kakarot-dev** [comment]
@Orchit07 ill be changing the event to the the only push to master or dev and next

**Review by Deivu — CHANGES_REQUESTED** [review]
https://github.com/Deivu/Shoukaku/blob/5800822bbe44ef7f431500bdf80cb7ce0a049c2e/src/guild/ShoukakuConnection.js#L156
Should be `options.deaf`
https://github.com/Deivu/Shoukaku/blob/5800822bbe44ef7f431500bdf80cb7ce0a049c2e/src/guild/ShoukakuConnection.js#L157
Should be `options.mute`
https://github.com/Deivu/Shoukaku/blob/5800822bbe44ef7f431500bdf80cb7ce0a049c2e/src/node/ShoukakuSocket.js#L207


Change to:
```js
if (isNaN(optios.shardId) || !options.guildId || !options.channelId)
```
and modify the error message accordingly


Mark
https://github.com/Deivu/Shoukaku/blob/5800822bbe44ef7f431500bdf80cb7ce0a049c2e/types/struct/ShoukakuFilter.d.ts#L39
And
https://github.com/Deivu/Shoukaku/blob/5800822bbe44ef7f431500bdf80cb7ce0a049c2e/types/struct/ShoukakuFilter.d.ts#L66
As nullable

**Comment by kakarot-dev** [comment]
Will start doing it.

and @Orchit07 if there is no changes in the docs, the action will mark the repo as unsuccessful https://github.com/kakarot-dev/Shoukaku/actions/runs/1103634253
Is there anyway to make it to not show the ❌

**Comment by kakarot-dev** [comment]
https://github.com/kakarot-dev/Shoukaku/blob/8de6344d6b11b3fe12b5c5fbea076f46904e1cb2/src/guild/ShoukakuConnection.js#L167
Wont this line error if deaf and mute are not provided?

**Comment by Deivu** [comment]
> https://github.com/kakarot-dev/Shoukaku/blob/next/src/guild/ShoukakuConnection.js#L167
> Wont this line error if deaf and mute are not provided?
Not really

**Comment by Orchit07** [comment]
> https://github.com/kakarot-dev/Shoukaku/blob/next/src/guild/ShoukakuPlayer.js#L2A
> Wont this line error if deaf and mute are not provided?

image
i think, that's not a problem

**Comment by kakarot-dev** [comment]
oki then, 
one last question, why is Shoukaku not handling queues internally?

**Comment by Deivu** [comment]
> oki then,
> one last question, why is Shoukaku not handling track queues internally? ( only a question )

No point on doing so, most people will want to customize their queues accordingly, and since the beginning, I only wanted to handle the library <-> lavalink interface, anything that falls out of scope on that is something the developer that using the library will do so

**Comment by kakarot-dev** [comment]
yep! understood 

and with that, i think pr is ready for review

**Review by Deivu — APPROVED** [review]

**Comment by Deivu** [comment]
Last thing, I assume this is tested?

**Comment by kakarot-dev** [comment]
@Orchit07 tested it.

**Pull request merged**
