### PR TITLE
Typings again

### PR DESCRIPTION
**Pull request by hydrox19**
I have fixed a few typings and have added some

### CODE REVIEW

**Comment by kakarot-dev** [comment]
The last commit is so true lol

**Comment by Deivu** [comment]
The typings is missing on ChannelMix and LowPass, will be merging once that is included

**Comment by hydrox19** [comment]
> The typings is missing on ChannelMix and LowPass, will be merging once that is included

Yeah I was coding while getting my hair trimmed sounds weird but yeah I'm home now will do in few minutes

**Comment by Deivu** [comment]
The types for channelmix and lowpass is not yet added, and player event "disconnect" has no types yet as well

**Comment by Deivu** [comment]
> The types for channelmix and lowpass is not yet added, and player event "disconnect" has no types yet as well

Refer Here https://github.com/Deivu/Shoukaku/blob/2b96e7728019e1399c4fce2957538b8ae345645d/src/guild/ShoukakuPlayer.js#L322 
and the function below that

Nevermind the disconnect, I actually changed how that works

**Comment by Deivu** [comment]
Seems good, merging this. Thanks for the PR

**Pull request merged**
