### PR TITLE
Removes discord.js-light from package.json

### PR DESCRIPTION
**Pull request by kakarot-dev**
There is no use of djs-light now cuz v13 of djs has cache control in built
So this pr removes the package

### CODE REVIEW

**Comment by Deivu** [comment]
we could actually remove discord.js as well, as next can be integrated on other libraries

**Comment by kakarot-dev** [comment]
Ok

**Comment by hydrox19** [comment]
I'll update the typings

**Comment by kakarot-dev** [comment]
K
ill remove eris too xd

**Comment by kakarot-dev** [comment]
And i dont think typings need updating, but ok

**Comment by kakarot-dev** [comment]
I think pr done
do you need to do something else?

**Comment by hydrox19** [comment]
Okay everything looks fine, wait for Saya to review it.

**Comment by kakarot-dev** [comment]
Before i do anything else, can i rename the variable to camelCase ?
it feels kinda weird `guildID` => `guildId`

**Comment by hydrox19** [comment]
Well, I don't think those are needed Shouka is not limited to discord.js anymore. so there's no point in renaming the `guildID` => `guildId`.

**Comment by kakarot-dev** [comment]
Oh, ok then atleast most of the discord api libs ive used have camelcase, so i asked it out of habit xd

**Comment by Deivu** [comment]
I'm still thinking about that, usually rather than camel casing, I usually go with design choices like guild instead of guildID or guildId, I just did it that way so people *knew* it's an id, and not a structure, you could talk about that on v2 pr, though I do think guild is better than guildID or guildId

**Comment by hydrox19** [comment]
Well, we need a strong point to use it after all. If we wanna use `guild` instead of `guildID` which clearly tells us that we have to pass a Guild ID not anything else.

**Comment by kakarot-dev** [comment]
Im okay with whatever you guys decide
i just wanted to contribute :)

**Comment by kakarot-dev** [comment]
But I honestly think that if possible camelCase should be used.

**Comment by Deivu** [comment]
Seems good

**Pull request merged**
